import type { Fighter } from "../simulation/types";

export const FIGHTERS: Fighter[] = [
  {
    id: "golden-soul-maiden",
    name: "김아영",
    title: "금혼옥녀",
    concept: "옥빛 혼을 매단 검으로 마음과 기세를 묶는다",
    maxHp: 100,
    weakDamage: 12,
    strongDamage: 24,
    specialDamage: 50,
    attackBias: { Special: 2, AttackFail: 1 },
    defenseBias: { Counter: 2, DefenseFail: 1 },
    spriteKey: "fighter-golden-soul-maiden",
    portraitKey: "portrait-kim-ayoung",
    portraitPath: "/assets/portraits/kim-ayoung.png",
    portraitThumbPath: "/assets/portraits/thumbs/kim-ayoung.png",
    selectIntroVideoPath: "/assets/select-reveals/golden-soul-maiden-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/golden-soul-maiden-final.png",
    awakened: {
      name: "무신아영",
      title: "진노의 화신",
      concept: "분노에 사로잡힌 주먹으로 모든 것을 부서뜨린다",
      portraitPath: "/assets/awakened-select/golden-soul-maiden-base.png",
      introVideoPath: "/assets/awakened-select/golden-soul-maiden-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/golden-soul-maiden-final.png",
    },
    palette: { primary: 0xbe185d, secondary: 0xfbcfe8, accent: 0xf472b6 },
  },
  {
    id: "seal-judge",
    name: "이한솔",
    title: "승인판관",
    concept: "승인의 옥새를 들어 승패를 판결하는 금빛 판관",
    maxHp: 102,
    weakDamage: 12,
    strongDamage: 25,
    specialDamage: 47,
    attackBias: { StrongAttack: 2, Special: 1 },
    defenseBias: { Block: 3, Counter: 2 },
    spriteKey: "fighter-seal-judge",
    portraitKey: "portrait-lee-hansol",
    portraitPath: "/assets/portraits/lee-hansol.png",
    portraitThumbPath: "/assets/portraits/thumbs/lee-hansol.png",
    selectIntroVideoPath: "/assets/select-reveals/seal-judge-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/seal-judge-final.png",
    awakened: {
      name: "fㅔ르리페",
      title: "노핸들쾌남",
      concept: "핸들은 내려놓고 자유주행으로 판세를 흔든다",
      portraitPath: "/assets/awakened-select/seal-judge-base.png",
      introVideoPath: "/assets/awakened-select/seal-judge-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/seal-judge-final.png",
    },
    palette: { primary: 0x854d0e, secondary: 0xfde68a, accent: 0xfacc15 },
  },
  {
    id: "thunder-discipline",
    name: "손경현",
    title: "벽력훈계",
    concept: "천둥 같은 한마디와 곤봉으로 흐름을 끊는 훈계가",
    maxHp: 104,
    weakDamage: 10,
    strongDamage: 29,
    specialDamage: 45,
    attackBias: { StrongAttack: 5, AttackFail: 2 },
    defenseBias: { Counter: 1, DefenseFail: 2 },
    spriteKey: "fighter-thunder-discipline",
    portraitKey: "portrait-son-gyeonghyeon",
    portraitPath: "/assets/portraits/son-gyeonghyeon.png",
    portraitThumbPath: "/assets/portraits/thumbs/son-gyeonghyeon.png",
    selectIntroVideoPath: "/assets/select-reveals/thunder-discipline-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/thunder-discipline-final.png",
    awakened: {
      name: "손경현 Jr. 20세",
      title: "연심풍류객",
      concept: "웃음과 향풍으로 상대의 흐름을 흐트러뜨린다",
      portraitPath: "/assets/awakened-select/thunder-discipline-base.png",
      introVideoPath: "/assets/awakened-select/thunder-discipline-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/thunder-discipline-final.png",
    },
    palette: { primary: 0x78350f, secondary: 0xfef3c7, accent: 0xf59e0b },
  },
  {
    id: "abacus-ghost",
    name: "김형민",
    title: "산판귀수",
    concept: "산판알을 귀수처럼 굴려 수 싸움을 장악한다",
    maxHp: 100,
    weakDamage: 12,
    strongDamage: 26,
    specialDamage: 44,
    attackBias: { WeakAttack: 3, Special: 1 },
    defenseBias: { Counter: 4 },
    spriteKey: "fighter-abacus-ghost",
    portraitKey: "portrait-kim-hyungmin",
    portraitPath: "/assets/portraits/kim-hyungmin.png",
    portraitThumbPath: "/assets/portraits/thumbs/kim-hyungmin.png",
    selectIntroVideoPath: "/assets/select-reveals/abacus-ghost-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/abacus-ghost-final.png",
    awakened: {
      name: "형즈코",
      title: "애교요희",
      concept: "분홍빛 요력과 귀여움으로 승부의 결을 비튼다",
      portraitPath: "/assets/awakened-select/abacus-ghost-base.png",
      introVideoPath: "/assets/awakened-select/abacus-ghost-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/abacus-ghost-final.png",
    },
    palette: { primary: 0x14532d, secondary: 0xdcfce7, accent: 0x22c55e },
  },
  {
    id: "emuji",
    name: "김효진",
    title: "에무지",
    concept: "청색 음파와 기민한 손놀림으로 박자를 빼앗는다",
    maxHp: 102,
    weakDamage: 12,
    strongDamage: 27,
    specialDamage: 47,
    attackBias: { StrongAttack: 3, Special: 1 },
    defenseBias: { Block: 2, Counter: 2 },
    spriteKey: "fighter-emuji",
    portraitKey: "portrait-kim-hyojin",
    portraitPath: "/assets/portraits/kim-hyojin.png",
    portraitThumbPath: "/assets/portraits/thumbs/kim-hyojin.png",
    selectIntroVideoPath: "/assets/select-reveals/emuji-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/emuji-final.png",
    awakened: {
      name: "김효진",
      title: "직언난타",
      concept: "반골청언문으로 정곡을 두드리는 청색 난타",
      portraitPath: "/assets/awakened-select/emuji-base.png",
      introVideoPath: "/assets/awakened-select/emuji-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/emuji-final.png",
    },
    palette: { primary: 0x075985, secondary: 0xbae6fd, accent: 0x0ea5e9 },
  },
  {
    id: "seahorse-overlord",
    name: "이창주",
    title: "해마패왕",
    concept: "붉은 해마의 기운을 두른 패로 정면을 제압한다",
    maxHp: 98,
    weakDamage: 14,
    strongDamage: 24,
    specialDamage: 48,
    attackBias: { Special: 1, AttackFail: -2 },
    defenseBias: { Dodge: 5 },
    spriteKey: "fighter-seahorse-overlord",
    portraitKey: "portrait-lee-changju",
    portraitPath: "/assets/portraits/lee-changju.png",
    portraitThumbPath: "/assets/portraits/thumbs/lee-changju.png",
    selectIntroVideoPath: "/assets/select-reveals/seahorse-overlord-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/seahorse-overlord-final.png",
    awakened: {
      name: "이창주",
      title: "레버리지",
      concept: "배율의 검으로 상승과 하락을 함께 베어낸다",
      portraitPath: "/assets/awakened-select/seahorse-overlord-base.png",
      introVideoPath: "/assets/awakened-select/seahorse-overlord-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/seahorse-overlord-final.png",
    },
    palette: { primary: 0x991b1b, secondary: 0xfca5a5, accent: 0xef4444 },
  },
  {
    id: "longing-soul",
    name: "장정인",
    title: "원하연혼",
    concept: "연혼의 장식에 그리움을 묶어 상대의 틈을 부른다",
    maxHp: 96,
    weakDamage: 13,
    strongDamage: 25,
    specialDamage: 46,
    attackBias: { WeakAttack: 3, Special: 2 },
    defenseBias: { Dodge: 3, Counter: 2 },
    spriteKey: "fighter-longing-soul",
    portraitKey: "portrait-jang-jeongin",
    portraitPath: "/assets/portraits/jang-jeongin.png",
    portraitThumbPath: "/assets/portraits/thumbs/jang-jeongin.png",
    selectIntroVideoPath: "/assets/select-reveals/longing-soul-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/longing-soul-final.png",
    awakened: {
      name: "장정인",
      title: "취운술사",
      concept: "백년가약의 춤으로 인연의 칼날을 휘두른다",
      portraitPath: "/assets/awakened-select/longing-soul-base.png",
      introVideoPath: "/assets/awakened-select/longing-soul-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/longing-soul-final.png",
    },
    palette: { primary: 0x581c87, secondary: 0xf3e8ff, accent: 0xc084fc },
  },
  {
    id: "truth-tracker",
    name: "권용철",
    title: "진실추적",
    concept: "붉은 렌즈로 허점을 추적해 진실의 일격을 꽂는다",
    maxHp: 100,
    weakDamage: 12,
    strongDamage: 28,
    specialDamage: 48,
    attackBias: { StrongAttack: 4, Special: 1 },
    defenseBias: { Block: 3, Counter: 3 },
    spriteKey: "fighter-truth-tracker",
    portraitKey: "portrait-kwon-yongcheol",
    portraitPath: "/assets/portraits/kwon-yongcheol.png",
    portraitThumbPath: "/assets/portraits/thumbs/kwon-yongcheol.png",
    selectIntroVideoPath: "/assets/select-reveals/truth-tracker-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/truth-tracker-final.png",
    awakened: {
      name: "용잔",
      title: "혈색첨삭",
      concept: "붉은 첨삭으로 죄를 기록하고 정의를 새긴다",
      portraitPath: "/assets/awakened-select/truth-tracker-base.png",
      introVideoPath: "/assets/awakened-select/truth-tracker-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/truth-tracker-final.png",
    },
    palette: { primary: 0x7f1d1d, secondary: 0xfecaca, accent: 0xef4444 },
  },
  {
    id: "glass-heart",
    name: "김태우",
    title: "유리심장",
    concept: "깨질 듯 투명한 내공으로 충격을 흘려내는 수비가",
    selectionStatus: "GlobalBan",
    maxHp: 112,
    weakDamage: 10,
    strongDamage: 22,
    specialDamage: 44,
    attackBias: { WeakAttack: 2 },
    defenseBias: { Block: 5, Dodge: 2 },
    spriteKey: "fighter-glass-heart",
    portraitKey: "portrait-kim-taewoo",
    portraitPath: "/assets/portraits/kim-taewoo.png",
    portraitThumbPath: "/assets/portraits/thumbs/kim-taewoo.png",
    selectIntroVideoPath: "/assets/select-reveals/glass-heart-intro.mp4",
    selectFinalPortraitPath: "/assets/select-reveals/glass-heart-final.png",
    awakened: {
      name: "김태우",
      title: "희비쌍면",
      concept: "웃음과 울음의 양면으로 흐름을 양분한다",
      portraitPath: "/assets/awakened-select/glass-heart-base.png",
      introVideoPath: "/assets/awakened-select/glass-heart-intro.mp4",
      finalPortraitPath: "/assets/awakened-select/glass-heart-final.png",
    },
    palette: { primary: 0x164e63, secondary: 0xcffafe, accent: 0x22d3ee },
  },
];

export const BASE_FIGHTERS = FIGHTERS;
export const SELECTABLE_FIGHTERS = FIGHTERS.filter((fighter) => fighter.selectionStatus !== "GlobalBan");

export const FIGHTER_BY_ID = Object.fromEntries(FIGHTERS.map((fighter) => [fighter.id, fighter])) as {
  [Key in Fighter["id"]]: Fighter;
};

export function isFighterGloballyBanned(fighter: Fighter | Fighter["id"]) {
  const target = typeof fighter === "string" ? FIGHTER_BY_ID[fighter] : fighter;
  return target.selectionStatus === "GlobalBan";
}
